name: CoinGecko Listings

on:
  schedule:
    - cron: '*/30 * * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          BOT_TOKEN: ${{ 8483160777:AAG872i0TMAxuAXcB6ZhqjcooPSoapo_y-U }}
          CHAT_ID: ${{ 8483160777 }}
